ROWS = 11  # 4 water, 4 road, 1 middle stage, 1 starting area, 1 end area
COLS = 13

FROG_SIZE = 40
PADDING = 20

HORIZONTAL_GAP = FROG_SIZE + PADDING + 2
VERTICAL_GAP = FROG_SIZE + PADDING + 2

HG = HORIZONTAL_GAP
VG = VERTICAL_GAP

SCREEN_WIDTH = COLS * HORIZONTAL_GAP
SCREEN_HEIGHT = ROWS * VERTICAL_GAP
FRAME_RATE = 24

DEBUG = True
